export const LABELS = Object.freeze({
  institutions: 'Instituciones',
  institution: 'Institución',
  bussinessName: 'Nombre comercial',
  nit: 'NIT',
  legalRepresentative: 'Representante legal',
  ciLegalRepresentative: 'CI representante legal',
  billingName: 'Nombre de facturación',
  clientType: 'Tipo de cliente',
  businessName: 'Nombre comercial',
  institutionName: 'Nombre de la institución',
  institutionAddress: 'Dirección de la institución',
  institutionPhoneNumber: 'Teléfono de la institución',
  account: 'Cuenta',
  yes: 'Si',
  no: 'No',
  materials: 'Materiales',
  cooperatives: 'Cooperativas',
  lots: 'Lotes',
  typeMaterials: 'Tipos de materiales',
  mines: 'Minas',
  purpose: 'Propósito',
  delete: 'Eliminar',
  cancelInvoice: 'Anular factura',
  getInto: 'Ingresar',
  auxiliary: 'Auxiliar',
  nim: 'NIM',
  configurations: 'Configuraciones',
  value: 'Valor',
  consolidationDay: 'Día de consolidación',
  activity: 'Actividad',
  product: 'Producto',
  sivelCode: 'Código SIVEL',
  user: 'Usuario',
  password: 'Contraseña',
  sivelName: 'Nombre SIVEL',
  externalCode: 'Código externo',
  externalId: 'ID externo',
  currencyCoreId: 'ID moneda de Núcleo',
  documentTypeCoreId: 'ID tipo de documento de Núcleo',
  detail: 'Detalle',
  concept: 'Concepto',
  conceptId: 'ID de concepto',
  conciliation: 'Conciliación',
  conciliationAmount: 'Monto conciliado',
  item: 'Item',
  finalAmount: 'Monto final',
  conceptCode: 'Código de concepto',
  conceptName: 'Nombre de concepto',
  isHomologated: 'Esta homologado?',
  branch: 'Sucursal',
  pointOfSale: 'Punto de venta',
  branchSivel: 'Sucursal Sivel',
  pointOfSaleSivel: 'Punto de venta Sivel',
  coreCompanyId: 'ID empresa de Núcleo',
  activityCode: 'Código de actividad',
  productCode: 'Código de producto',
  systemCode: 'Código de sistema',
  homologation: 'Homologación',
  system: 'Sistema',
  modeLight: 'Modo claro',
  modeDark: 'Modo oscuro',
  itemTypeCode: 'Código de tipo de item',
  itemType: 'Tipo de item',
  productDetail: 'Detalle de producto',
  expenseIncomeConcept: 'Concepto de ingreso/gasto',
  currencyCore: 'Moneda de Núcleo',
  currencySivel: 'Moneda de Sivel',
  reasonCancel: 'Motivo de cancelación',
  companySivel: 'Empresa de Sivel',
  documentTypeSivel: 'Tipo de documento de Sivel',
  invoiceTypeSivel: 'Tipo de factura de Sivel',
  invoiceNumber: 'Número de factura',
  issueNumber: 'Número de conciliación',
  companyCore: 'Empresa de Núcleo',
  company: 'Empresa',
  clientName: 'Nombre cliente',
  clientDocNumber: 'Número documento cliente',
  clientEmail: 'Correo cliente',
  paymentMethod: 'Método de pago',
  actions: 'Acciones',
  total: 'Total',
  month: 'Mes',
  year: 'Año',
  reason: 'Motivo',
  totals: 'Totales',
  giftCard: 'Tarjeta de regalo (Gift card)',
  discount: 'Descuento',
  documentTypeCore: 'Tipo de documento de Núcleo',
  invoiceType: 'Tipo de factura',
  totalConciliatedAmount: 'Monto total conciliado',
  codeSivel: 'Código Sivel',
  department: 'Departamento',
  code: 'Código',
  taxCreditIVA: 'Crédito fiscal iva',
  taxDebitIVA: 'Débito fiscal iva',
  cuf: 'CUF',
  customer: 'Cliente',
  nameOrSocialReason: 'Nombre / Razón social',
  companyDepartment: 'Departamento Contable',
  currency: 'Moneda',
  date: 'Fecha',
  totalNationalExpensesFob: 'Total costos y gastos nacionales',
  totalInternationalExpensesCost: 'Total Costos y gastos internacionales',
  createdBy: 'Creado por',
  totalDetail: 'Total detalle',
  totalGeneral: 'Total general',
  totalAmountToPay: 'Total a pagar',
  totalAmountOriginal: 'Monto total original',
  amountOriginal: 'Monto total original',
  creationDate: 'Fecha creación',
  issueDate: 'Fecha emisión',
  exchangeRate: 'Tipo de cambio',
  email: 'Correo electrónico',
  additionalInfo: 'Información adicional',
  nationalExpensesCost: 'Gastos nacionales',
  internationalExpensesCost: 'Gastos internacionales',
  numberPackagesDescription: 'Descripción del número de paquete',
  address: 'Dirección',
  supplierGroup: 'Grupo de proveedor',
  suppliers: 'Proveedores',
  cotization: 'Cotización',
  phone: 'Teléfono',
  docNumber: 'Número de documento',
  totalAmountExchanged: 'Monto total cambiado',
  docType: 'Tipo de documento',
  clientDocType: 'Tipo de documento cliente',
  complement: 'Complemento',
  customerMarket: 'Mercado de clientes',
  status: 'Estado',
  creditDebitNumber: 'Número de crédito/débito',
  cashAAmountCreditDebit: 'Monto efectivo crédito/débito',
  amountDiscountCreditDebit: 'Descuento crédito/débito',
  totalRefundedAmount: 'Monto total reintegrado',
  marketType: 'Tipo de mercado',
  destinationPlace: 'Lugar de destino',
  destinationPort: 'Puerto de destino',
  newAmount: 'Nuevo monto',
  countryCode: 'Código de país',
  countryCodeSivel: 'Código de país de Sivel',
  incoterm: 'INCOTERM',
  name: 'Nombre',
  nameCore: 'Nombre de Núcleo',
  budgetSummary: 'Ppto. Recurso',
  budgetExpense: 'Ppto. Gasto',
  socialReason: 'Razón social',
  incomeConcept: 'Concepto de venta',
  import: 'Importe',
  budgetItem: 'Partida',
  registerManager: 'Responsable de registro',
  expense: 'Gasto',
  resource: 'Recurso',
  conceptSale: 'Concepto de venta',
  disaccount: 'Descuento',
  initials: 'Iniciales',
  organizationalUnit: 'Unidad Organizativa',
  programmaticCategory: 'Categoría Programática',
  program: 'Programa',
  project: 'Proyecto',
  persons: 'Personas',
  person: 'Persona',
  fundingSource: 'Fuente de financiamiento',
  fundingOrganization: 'Organización financiadora',
  programmaticStructure: 'Estructura Programática',
  regional: 'Regional',
  financier: 'Financiador',
  totalAmount: 'Monto total',
  subTotal: 'Subtotal',
  description: 'Descripción',
  prefix: 'Prefijo',
  initialNumber: 'Número inicial',
  surname: 'Apellido',
  productDescription: 'Descripción del producto',
  homologationDescription: 'Descripción de homologación',
  discountAmount: 'Descuento',
  nandinaCode: 'Código nandina',
  discountAmountBc: 'Monto de descuento en Bs.',
  accountName: 'Nombre de cuenta',
  amount: 'Monto',
  budgetItemName: 'Nombre de partida',
  unitPrice: 'Precio unitario',
  unitMesurement: 'Unidad de medida',
  quantity: 'Cantidad',
  expenseBudget: 'Presupuesto de gasto',
  expenseBudgetSummary: 'Presupuesto de gasto',
  resourceBudgetSummary: 'Presupuesto de recurso',
  listOfCompanies: 'Lista de empresas',
  cajaNacional: 'Caja Nacional',
  fedecomin: 'FEDECOMIN',
  fencomin: 'FENCOMIN',
  comibol: 'COMIBOL',
  wilstermann: 'WILSTERMANN',
  cooperativeContribution: 'Contribución cooperativa',
  miningRoyalties: 'Regalías mineras',
} as const);

export const TITLES = Object.freeze({
  customerList: 'Listado de clientes',
  customerAccountList: 'Listado de cuentas por cliente',
  homologationList: 'Listado de homologaciones',
  homologations: 'Homologaciones',
  items: 'Items',
  currencies: 'Monedas',
  invoiceDetails: 'Detalles de factura',
  customers: 'Clientes',
  invoices: 'Facturas',
  companies: 'Empresas',
  documentTypes: 'Tipos de documento',
  invoiceTypes: 'Tipos de factura',
  invoiceList: 'Listado de facturas',
  invoiceDetailList: 'Listado de detalles de factura',
} as const);

export const LABEL_BUTTONS = Object.freeze({
  create: 'Crear',
  cancel: 'Cancelar',
  clear: 'Limpiar',
  delete: 'Eliminar',
  edit: 'Editar',
  export: 'Exportar',
  expand: 'Mas información',
  filter: 'Filtrar',
  info: 'Info',
  reload: 'Actualizar',
  save: 'Guardar',
  cancelInvoice: 'Anular factura',
  printInvoice: 'Imprimir factura',
  search: 'Buscar',
  unassign: 'Desasignar',
  assign: 'Asignar',
  approve: 'Aprobar',
  deny: 'Rechazar',
  print: 'Imprimir',
} as const);

export const TOOLTIPS = Object.freeze({
  create: 'Crear',
  clear: 'Limpiar',
  clearFilters: 'Limpiar filtros',
  delete: 'Eliminar',
  edit: 'Editar',
  export: 'Exportar',
  info: 'Info',
  reload: 'Actualizar',
  selectColumns: 'Seleccione las columnas',
  homologateItem: 'Homologar item',
  close: 'Cerrar',
  save: 'Guardar',
  cancel: 'Cancelar',
  editableField: 'Este campo es editable',
  printInvoice: 'Imprimir factura',
  conciliateInvoice: 'Conciliar factura',
  debitInvoice: 'Debitar factura',
  cancelInvoice: 'Anular factura',
  reverseAnnulment: 'Revertir anulación',
  issueInvoice: 'Emitir factura',
  massEditing: 'Edición masiva',
  massDeleting: 'Eliminación masiva',
  acceptChanges: 'Aceptar cambios',
  dismissChanges: 'Descartar Cambio',
  editRow: 'Editar fila',
  deleteRow: 'Eliminar fila',
} as const);

export const PLACEHOLDERS = Object.freeze({
  select: 'Seleccione una opción...',
  search: 'Buscar...',
  searchInCurrentView: 'Buscar en la vista actual',
  onDemandFilterInput: 'Ingrese 3 o más caracteres para buscar'
} as const);
